import type { MockStore } from "./store";

/**
 * The full `configuration` payload. The app queries Stash's `Configuration` document
 * which selects essentially every field, so all non-null fields must be present.
 * Values aim to match a fresh, unconfigured Stash install (validated against a real
 * instance by `test/conformance`).
 */
export function buildConfiguration(store: MockStore) {
  return {
    general: {
      stashes: [],
      databasePath: "",
      backupDirectoryPath: "",
      deleteTrashPath: "",
      generatedPath: "",
      metadataPath: "",
      configFilePath: "",
      scrapersPath: "",
      pluginsPath: "",
      cachePath: "",
      blobsPath: "",
      blobsStorage: "DATABASE",
      ffmpegPath: "",
      ffprobePath: "",
      calculateMD5: false,
      videoFileNamingAlgorithm: "OSHASH",
      parallelTasks: 1,
      previewAudio: true,
      previewSegments: 12,
      previewSegmentDuration: 0.75,
      previewExcludeStart: "0",
      previewExcludeEnd: "0",
      previewPreset: "ultrafast",
      maxMarkerPreviewDuration: 0,
      defaultMarkerPreviewDuration: 20,
      useCustomSpriteInterval: false,
      spriteInterval: 30,
      minimumSprites: 10,
      maximumSprites: 500,
      spriteScreenshotSize: 160,
      transcodeHardwareAcceleration: false,
      maxTranscodeSize: null,
      maxStreamingTranscodeSize: null,
      writeImageThumbnails: true,
      createImageClipsFromVideos: false,
      apiKey: "",
      username: "",
      password: "",
      maxSessionAge: 30,
      logFile: null,
      logOut: true,
      logLevel: "Info",
      logAccess: true,
      logFileMaxSize: 0,
      createGalleriesFromFolders: true,
      galleryCoverRegex: "",
      videoExtensions: [".mp4", ".m4v", ".wmv", ".avi", ".mov", ".mkv", ".webm"],
      imageExtensions: [".jpg", ".jpeg", ".png", ".gif", ".webp"],
      galleryExtensions: [".zip"],
      excludes: [],
      imageExcludes: [],
      customPerformerImageLocation: null,
      stashBoxes: [],
      pythonPath: "",
      transcodeInputArgs: [],
      transcodeOutputArgs: [],
      liveTranscodeInputArgs: [],
      liveTranscodeOutputArgs: [],
      drawFunscriptHeatmapRange: false,
      scraperPackageSources: [],
      pluginPackageSources: [],
    },
    interface: {
      menuItems: ["scenes", "images", "groups", "markers", "galleries", "performers", "studios", "tags"],
      soundOnPreview: false,
      wallShowTitle: true,
      wallPlayback: "video",
      showScrubber: true,
      maximumLoopDuration: 0,
      noBrowser: false,
      notificationsEnabled: true,
      autostartVideo: true,
      autostartVideoOnPlaySelected: true,
      continuePlaylistDefault: false,
      showStudioAsText: false,
      css: "",
      cssEnabled: false,
      javascript: "",
      javascriptEnabled: false,
      customLocales: "",
      customLocalesEnabled: false,
      language: "en-GB",
      sfwContentMode: false,
      imageLightbox: {
        slideshowDelay: 5000,
        displayMode: "FIT_XY",
        scaleUp: true,
        resetZoomOnNav: true,
        scrollMode: "PAN_Y",
        scrollAttemptsBeforeChange: 0,
      },
      disableDropdownCreate: {
        performer: false,
        tag: false,
        studio: false,
        movie: false,
        gallery: false,
      },
      handyKey: null,
      funscriptOffset: 0,
      useStashHostedFunscript: false,
    },
    dlna: {
      serverName: "mock-stash",
      enabled: false,
      port: 1338,
      whitelistedIPs: [],
      interfaces: [],
      videoSortOrder: "title",
    },
    scraping: {
      scraperUserAgent: null,
      scraperCDPPath: null,
      scraperCertCheck: false,
      excludeTagPatterns: [],
    },
    defaults: {
      scan: null,
      identify: null,
      autoTag: null,
      generate: null,
      deleteFile: false,
      deleteGenerated: false,
    },
    ui: store.uiConfig,
    plugins: store.pluginConfig,
  };
}
