import { statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { Fixtures, SceneRecord, VideoFileRecord } from "./types";

const here = path.dirname(fileURLToPath(import.meta.url));
export const MEDIA_DIR = path.resolve(here, "media");

function fileSize(name: string): number {
  try {
    return statSync(path.join(MEDIA_DIR, name)).size;
  } catch {
    return 100_000;
  }
}

/**
 * Deterministic media fixtures generated by `scripts/generate-media.mjs` (ffmpeg lavfi
 * testsrc2 — see that file). These same files also seed the real-Stash conformance
 * containers so both servers serve byte-identical media.
 */
export const MEDIA_SPECS = [
  { name: "scene-1", duration: 12, width: 320, height: 180, codec: "h264", ext: ".mp4", mimeType: "video/mp4" },
  { name: "scene-2", duration: 12, width: 320, height: 180, codec: "vp8", ext: ".webm", mimeType: "video/webm" },
  { name: "scene-3", duration: 12, width: 180, height: 320, codec: "h264", ext: ".mp4", mimeType: "video/mp4" },
  { name: "scene-4", duration: 10, width: 240, height: 240, codec: "h264", ext: ".mp4", mimeType: "video/mp4" },
] as const;

export type MediaSpec = (typeof MEDIA_SPECS)[number];

export function mediaFileFor(sceneId: string): MediaSpec {
  // scenes 5-8 reuse the media of scenes 1-4
  const base = sceneId.replace(/^scene-([5-8])$/, (_, d) => `scene-${Number(d) - 4}`);
  return MEDIA_SPECS.find((s) => s.name === base) ?? MEDIA_SPECS[0];
}

const CREATED_AT = "2024-01-01T00:00:00Z";
const UPDATED_AT = "2024-01-01T00:00:00Z";

function videoFileFor(sceneId: string, index: number): VideoFileRecord {
  const spec = mediaFileFor(sceneId);
  const size = fileSize(`${spec.name}${spec.ext}`);
  return {
    id: `${sceneId}-file-1`,
    path: `/data/media/${sceneId}${spec.ext}`,
    basename: `${sceneId}${spec.ext}`,
    parent_folder_id: "folder-media",
    size,
    mod_time: CREATED_AT,
    duration: spec.duration,
    video_codec: spec.codec,
    audio_codec: spec.ext === ".webm" ? "opus" : "aac",
    format: spec.ext === ".webm" ? "webm" : "mpeg4",
    width: spec.width,
    height: spec.height,
    frame_rate: 24,
    bit_rate: Math.round((size * 8) / spec.duration),
    fingerprints: [{ type: "oshash", value: `oshash-${sceneId}` }],
    created_at: CREATED_AT,
    updated_at: UPDATED_AT,
  };
}

function scene(
  id: string,
  title: string,
  date: string,
  tagIds: string[],
  performerIds: string[],
  overrides: Partial<SceneRecord> = {},
): SceneRecord {
  return {
    id,
    title,
    code: null,
    details: `Details for ${title}.`,
    director: null,
    urls: [],
    date,
    rating100: null,
    organized: false,
    interactive: false,
    interactive_speed: null,
    created_at: CREATED_AT,
    updated_at: UPDATED_AT,
    last_played_at: null,
    resume_time: 0,
    play_duration: 0,
    play_count: 0,
    play_history: [],
    o_history: [],
    files: [videoFileFor(id, 0)],
    studio_id: null,
    tag_ids: tagIds,
    performer_ids: performerIds,
    ...overrides,
  };
}

/**
 * The default fixture set: 8 scenes (enough for pagination with the default page size of
 * 5), 6 markers across the first 3 scenes, 5 tags, 3 performers, 1 studio and 4 saved
 * filters (2 scenes + 2 markers).
 */
export function createDefaultFixtures(): Fixtures {
  const scenes: SceneRecord[] = [
    scene("scene-1", "Aurora Ascending", "2024-03-01", ["tag-alpha", "tag-gamma"], ["performer-alice"], {
      studio_id: "studio-prism",
      // o_counter is derived from o_history (like real Stash v0.28)
      o_history: ["2024-03-02T10:00:00Z", "2024-03-03T11:00:00Z"],
      play_count: 3,
    }),
    scene("scene-2", "Blueprint Boulevard", "2024-02-15", ["tag-beta"], ["performer-alice", "performer-bob"], {
      studio_id: "studio-prism",
      rating100: 70,
    }),
    scene("scene-3", "Cascade Calm", "2024-04-10", ["tag-gamma"], ["performer-carol"]),
    scene("scene-4", "Drift Duration", "2023-12-25", ["tag-alpha", "tag-beta"], []),
    scene("scene-5", "Ember Evening", "2023-11-05", ["tag-delta"], ["performer-bob"]),
    scene("scene-6", "Foothill Flight", "2025-01-20", ["tag-alpha", "tag-epsilon"], ["performer-carol", "performer-alice"]),
    scene("scene-7", "Grotto Glow", "2025-02-14", ["tag-beta"], ["performer-bob"]),
    scene("scene-8", "Horizon Hush", "2023-08-30", ["tag-delta", "tag-gamma"], []),
  ];

  const markers = [
    {
      id: "marker-1",
      scene_id: "scene-1",
      title: "Intro",
      seconds: 1,
      end_seconds: null,
      primary_tag_id: "tag-alpha",
      tag_ids: [],
      created_at: CREATED_AT,
      updated_at: UPDATED_AT,
    },
    {
      id: "marker-2",
      scene_id: "scene-1",
      title: "Finale",
      seconds: 8,
      end_seconds: null,
      primary_tag_id: "tag-beta",
      tag_ids: ["tag-gamma"],
      created_at: CREATED_AT,
      updated_at: UPDATED_AT,
    },
    {
      id: "marker-3",
      scene_id: "scene-2",
      title: "Highlight",
      seconds: 3,
      end_seconds: null,
      primary_tag_id: "tag-gamma",
      tag_ids: [],
      created_at: CREATED_AT,
      updated_at: UPDATED_AT,
    },
    {
      id: "marker-4",
      scene_id: "scene-3",
      title: "Opening",
      seconds: 2,
      end_seconds: null,
      primary_tag_id: "tag-alpha",
      tag_ids: [],
      created_at: CREATED_AT,
      updated_at: UPDATED_AT,
    },
    {
      id: "marker-5",
      scene_id: "scene-3",
      title: "Peak",
      seconds: 7,
      end_seconds: null,
      primary_tag_id: "tag-beta",
      tag_ids: ["tag-alpha"],
      created_at: CREATED_AT,
      updated_at: UPDATED_AT,
    },
    {
      id: "marker-6",
      scene_id: "scene-2",
      title: "Loop Point",
      seconds: 9,
      end_seconds: null,
      primary_tag_id: "tag-alpha",
      tag_ids: [],
      created_at: CREATED_AT,
      updated_at: UPDATED_AT,
    },
  ];

  const tags = [
    "alpha", "beta", "gamma", "delta", "epsilon",
  ].map((name) => ({
    id: `tag-${name}`,
    name: name.charAt(0).toUpperCase() + name.slice(1),
    aliases: [],
    parent_ids: [],
    child_ids: [],
    created_at: CREATED_AT,
    updated_at: UPDATED_AT,
  }));

  const performers = [
    { id: "performer-alice", name: "Alice Amaze", gender: "FEMALE", birthdate: "1995-04-12", ethnicity: null, country: "US", disambiguation: null },
    { id: "performer-bob", name: "Bob Bold", gender: "MALE", birthdate: "1990-09-03", ethnicity: null, country: "CA", disambiguation: null },
    { id: "performer-carol", name: "Carol Chase", gender: "FEMALE", birthdate: "1998-12-25", ethnicity: null, country: "GB", disambiguation: null },
  ].map((p) => ({ ...p, created_at: CREATED_AT, updated_at: UPDATED_AT }));

  const studios = [
    {
      id: "studio-prism",
      name: "Prism Pictures",
      url: "https://example.com/prism",
      parent_studio_id: null,
      created_at: CREATED_AT,
      updated_at: UPDATED_AT,
    },
  ];

  const defaultScenesFilter = {
    id: "1",
    mode: "SCENES" as const,
    name: "All Scenes",
    find_filter: { q: "", page: null, per_page: null, sort: "date", direction: "DESC" as const },
    object_filter: {},
    ui_options: null,
  };

  const savedFilters = [
    defaultScenesFilter,
    {
      id: "2",
      mode: "SCENES" as const,
      name: "Alpha Scenes",
      find_filter: { q: "", page: null, per_page: null, sort: "title", direction: "ASC" as const },
      // Hierarchical criteria are saved by Stash's UI as {items, excluded, depth}
      // label values — not the flat id-list criterion input the API accepts.
      object_filter: {
        tags: {
          value: { items: [{ id: "tag-alpha", label: "Alpha" }], excluded: [], depth: -1 },
          modifier: "INCLUDES",
        },
      },
      ui_options: null,
    },
    {
      id: "3",
      mode: "SCENE_MARKERS" as const,
      name: "All Markers",
      find_filter: { q: "", page: null, per_page: null, sort: "scene_id", direction: "ASC" as const },
      object_filter: {},
      ui_options: null,
    },
    {
      id: "4",
      mode: "SCENE_MARKERS" as const,
      name: "Beta Markers",
      find_filter: { q: "", page: null, per_page: null, sort: "scene_id", direction: "ASC" as const },
      object_filter: {
        tags: {
          value: { items: [{ id: "tag-beta", label: "Beta" }], excluded: [], depth: -1 },
          modifier: "INCLUDES",
        },
      },
      ui_options: null,
    },
  ];

  return {
    scenes,
    markers,
    tags,
    performers,
    studios,
    savedFilters,
    pluginConfig: {},
    uiConfig: {
      // A fresh Stash install has no default filters; we provide one so the app has
      // something deterministic to load. `scenes` here mirrors SavedFilter id "1".
      defaultFilters: { scenes: defaultScenesFilter },
    },
  };
}
