name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history to produce change log
          path: stash-tv
          token: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        working-directory: stash-tv
        run: |
          yarn install
          yarn --cwd packages/stash-ui setup

      - name: Bump version and create release notes
        working-directory: stash-tv
        run: |
          COMMITTED_VERSION=$(jq -r '.version' package.json)
          PREVIOUS_VERSION=$(git describe --tags --match "v[0-9]*.[0-9]*.[0-9]*" --abbrev=0 | sed 's/^v//')
          jq ".version = \"$PREVIOUS_VERSION\"" package.json > package.tmp.json
          mv package.tmp.json package.json

          yarn release

          NEW_VERSION=$(jq -r '.version' package.json)
          if [[ "$PREVIOUS_VERSION" != "$NEW_VERSION" ]]; then
            echo "Version bumped from $PREVIOUS_VERSION to $NEW_VERSION"
          else
            echo "No version bump detected"
            jq ".version = \"$COMMITTED_VERSION\"" package.json > package.tmp.json
            mv package.tmp.json package.json
          fi

      - name: Build project
        working-directory: stash-tv
        run: yarn build

      # We check types after building because GraphQL related types are generated during build
      - name: TypeScript check
        working-directory: stash-tv
        run: tsc --noEmit

      - name: Clone stash-plugins repo
        uses: actions/checkout@v5
        with:
          repository: secondfolder/stash-plugins
          path: stash-plugins
          token: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Copy built files to stash-plugins
        run: |
          rm -rf stash-plugins/plugins/stash-tv
          mkdir -p stash-plugins/plugins/stash-tv
          cp -r stash-tv/packages/tv-plugin/dist/* stash-plugins/plugins/stash-tv/

      - name: Commit and push built project to stash-plugins
        working-directory: stash-plugins
        run: |
          VERSION=$(jq -r '.version' ../stash-tv/package.json)
          if [[ ! "$VERSION" == 0.0.0* ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add plugins/stash-tv
            git commit -m "ci: release stash-tv $VERSION"
            git push
          else
            echo "No publishable changes made since last version"
          fi

      - name: Create git tag release
        working-directory: stash-tv
        run: |
          VERSION=$(jq -r '.version' package.json)
          if [[ ! "$VERSION" == 0.0.0* ]]; then
            git tag "v$VERSION"
            git push origin "v$VERSION"
          else
            echo "No publishable changes made since last version"
          fi

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        working-directory: stash-tv
        run: |
          VERSION=$(jq -r '.version' package.json)
          RELEASE_NOTES_FILE=".release-notes/$VERSION.md"
          if [[ -f "$RELEASE_NOTES_FILE" && ! "$VERSION" == 0.0.0* ]]; then
              gh release create "v$VERSION" --title "$VERSION" --notes-file "$RELEASE_NOTES_FILE"
          else
            echo "No release notes file found for $VERSION or version is 0.0.0*; skipping release creation."
          fi

      - name: Print publish info
        working-directory: stash-tv
        run: |
          VERSION=$(jq -r '.version' package.json)
          if [[ ! "$VERSION" == 0.0.0* ]]; then
            echo -e "### :rocket: Published new version: \n\`\`\`\n$VERSION\n\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "### No publishable changes made since last version" >> $GITHUB_STEP_SUMMARY
          fi